name: Release DEV build on master

# Push or merge into master
on:
  push:
    branches:    
      - master

jobs:
  mac:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install signing key
      run: |
        # this doesn't work
        base64 -D <<<  ${{ secrets.CERT_MACOS_TEMPORARY }} > cert.cer
        security import cert.cer "/Users/runner/Library/Keychains/login.keychain-db"
        security unlock-keychain -p '' "/Users/runner/Library/Keychains/login.keychain-db"
    - name: Release nightly version
      run: |
        make release_nightly